[profile.default]
src = 'contracts'
libs = ["lib"]

optimizer_runs = 1000
solc_version = "0.8.23"
evm_version = "shanghai"
bytecode_hash = "none"

block_base_fee_per_gas = 100000000 
block_number = 120000 
block_timestamp = 1640000000 
fs_permissions = [{access = "read-write", path = "./"}] 
gas_limit = 9223372036854775807 # the gas limit in tests

[fuzz]
max_test_rejects = 1000000
runs = 256